version: '3'

services:
  app:
    build: .
    environment:
      TZ: 'Asia/Tokyo'
      BUNDLE_PATH: /bundle/vendor
      DATABASE_URL: 'postgresql://tesao:tesao@db:5432'
      APPLICATION_DOMAIN: localhost:8081
    command: /bin/sh -c "rm -f /diving/tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    ports:
      - 3000:3000
    volumes:
      - .:/diving
      - bundles:/bundle
    links:
      - db
    depends_on:
      - db

  doc:
    image: swaggerapi/swagger-ui
    volumes:
      - ./openapi/reference/diving-map.yaml:/usr/share/nginx/html/diving-map.yaml
    environment:
      API_URL: diving-map.yaml
    ports:
      - 8081:8080

  db:
    image: postgres:9.6.22-alpine
    restart: always
    environment:
      POSTGRES_USER: tesao
      POSTGRES_PASSWORD: tesao
      POSTGRES_DB: diving
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  bundles:
  openapi_code:
  db_data:
