version: '3'

services:
  app:
    build:
      context: .
    environment:
      TZ: 'Asia/Tokyo'
      BUNDLE_PATH: /bundle/vendor
      DATABASE_URL: 'postgresql://tesao:tesao@db:5432'
    stdin_open: true
    tty: true
    command: /bin/sh -c "rm -f /usr/src/app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - bundles:/bundle
    links:
      - db
    depends_on:
      - db

  openapi:
    image: openapitools/openapi-generator-cli:latest-release
    command: generate -i /spec/openapi.yml -g ruby -o /local
    volumes:
      - ./app/openapi:/local
      - ./api-spec:/spec

  db:
    image: postgres:9.6.22-alpine
    restart: always
    environment:
      POSTGRES_USER: tesao
      POSTGRES_PASSWORD: tesao
      POSTGRES_DB: diving
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  bundles:
  db_data:
