version: '2.1'

executors:
  default:
    docker:
      - image: circleci/ruby:2.7.1
        environment:
          RAILS_ENV: test
          DATABASE_URL: psql://root:pass@127.0.0.1:5432
          SECRET_KEY_BASE: test_dive_map_api
      - image: circleci/postgres:9.6.22
        environment:
          POSTGRESS_PASSWORD: pass

jobs:
  build:
    executor: default
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: wait for DB
          command: ./dockernize -wait tcp://localhost:5432 -timeout 1m

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=18 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: run rubocop
          command: bundle exec rubocop

      - run:
          name: run rspec
          command: bundle exec rspec

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
